#!/usr/bin/env python3 

import urllib.request, urllib.error

# Point the script to a specific file with a list of fully formed URLs

with open("/Users/mattcordeiro/Documents/HOAH/Workspace/img_url_audit/remaining_img_2.txt") as f:
    urls = list(f) 

for url in urls:
    try:
        conn = urllib.request.urlopen(url)
    except urllib.error.HTTPError as e:
        # Return code error (e.g. 404, 501, ...)
        # ...
        print(url)
        print(e.code)
    except urllib.error.URLError as e:
        # Not an HTTP-specific error (e.g. connection refused)
        # ...
        print('URLError')
    else:
        # 200
        # ...
        print('200')
