#!/usr/bin/env python3

import os

os.system('open /Applications/Google\ Chrome.app')
os.system('open /Applications/Microsoft\ Office\ 2011/Microsoft\ Outlook.app')
os.system('open /Applications/Slack.app')
os.system('open /Applications/Google\ Chrome\ Canary.app')
os.system('open /System/Library/CoreServices/Finder.app')
