#!/usr/bin/python3 

import os

os.system('open /Applications/Google\ Chrome.app')
os.system('open /Applications/Microsoft\ Outlook.app')
os.system('open /Applications/Microsoft\ Teams.app')
os.system('open /System/Library/CoreServices/Finder.app')
