#-------------------------------------------------------------
# custom PATH
#-------------------------------------------------------------

export PATH=~/bin:$PATH
export PATH=~/bin/mc-dotfiles/bash:$PATH
export PATH=~/bin/mc-dotfiles/py:$PATH

#-------------------------------------------------------------
# custom commands
#-------------------------------------------------------------

source ~/bin/mc-dotfiles/bash/env
source ~/bin/mc-dotfiles/bash/alias
source ~/bin/mc-dotfiles/bash/prompt

#------------------------------------------------------------
# include for  
#------------------------------------------------------------


#if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
#  GIT_PROMPT_THEME=Default
#  source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
#fi

GIT_PS1_SHOWDIRTYSTATE=true

#if [ -f $(brew --prefix)/etc/bash_completion ]; then
#      . $(brew --prefix)/etc/bash_completion
#fi

#------------------------------------------------------------
# custom prompt
#------------------------------------------------------------

export PS1="\[\e[00;32m\]\h\[\e[0m\]\[\e[00;37m\].\[\e[0m\]\[\e[00;32m\]\u\[\e[0m\]\[\e[01;37m\][\[\e[0m\]\[\e[00;35m\]\w\[\e[0m\]\[\e[01;37m\]]\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[00;32m\]\\$:\[\e[0m\]$(__git_ps1)\$"

#------------------------------------------------------------
# custom ls
#------------------------------------------------------------

alias ls='ls -FHG'
#LS_COLORS='di=35:fi=0:ln=36:pi=0:so=0:bd=0:cd=0:or=0:ex=35:*rpm=0'
LSCOLORS='fxbhfxbxdxbxegedabagahad'
export LSCOLORS 
