#-------------------------------------------------------------
# custom commands
#-------------------------------------------------------------

source ~/bin/mc-dotfiles/bash/env
source ~/bin/mc-dotfiles/bash/alias
source ~/bin/mc-dotfiles/bash/prompt
